### ISSUE TITLE
Train/test/EDA scripts

### ISSUE THREAD

**Issue by ksedivyhaley** [UBC-MDS/DSCI_522_Group-308_Used-Cars#36]
Train/Test scripts should take input and output paths as arguments. Use the same script format as download.py - define and call main().

Train and EDA scripts need tests.

**Comment by pokrovskyy** [comment]
Thanks for the feedback on train / test scripts - they were amended to accept some useful parameters.

However, what kind of tests do you expect to have for train script? It's quite stochastic due to its nature. The only meaningful thing I could think about is add some input handling, like non-existent data files / invalid split sizes etc. Is that what you meant? Thanks!

**Comment by ksedivyhaley** [comment]
> The only meaningful thing I could think about is add some input handling, like non-existent data files / invalid split sizes etc. Is that what you meant?

That will do nicely!

**Comment by pokrovskyy** [comment]
Exactly! That’s what I’ve just done :) Thanks!
